### ISSUE TITLE
Do poprawy - package.json

### ISSUE THREAD

**Issue by Danon** [WojciechLiana/Angle-calculator#1]

**Comment by Danon** [comment]
Używasz `html-webpack-plugin`, ale ta zależność nie jest ustawiona w `package.json`. Kiedy próbowałem zainstalować apke u siebie dostałem:
```
PS C:\Users\Danon\Desktop\Angle-calculator> webpack build
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'html-webpack-plugin'
Require stack:
- C:\Users\Danon\Desktop\Angle-calculator\webpack.config.js
- C:\Users\Danon\AppData\Roaming\npm\node_modules\webpack\bin\convert-argv.js
- C:\Users\Danon\AppData\Roaming\npm\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\Danon\Desktop\Angle-calculator\webpack.config.js:2:27)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Danon\\Desktop\\Angle-calculator\\webpack.config.js',
    'C:\\Users\\Danon\\AppData\\Roaming\\npm\\node_modules\\webpack\\bin\\convert-argv.js',
    'C:\\Users\\Danon\\AppData\\Roaming\\npm\\node_modules\\webpack\\bin\\webpack.js'
  ]
}
```

**Comment by Danon** [comment]
Zadanko na dzisiaj: zrób sobie klona tego projektu w innym folderze i spróbuj to zainstalować :D Ja musiałem doinstalować z 10 zależności żeby uruchomić lokalnie apke.
